spring.application.name=store
spring.datasource.url=jdbc:sqlite:C:/Users/KEN219549/IdeaProjects/ECommerceLearning/SQLiteDB/eCommerce.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true